### ISSUE TITLE
🌟 [EPIC] Install Proxmox on our netcup Develop Server

### ISSUE THREAD

**Issue by Tirokk** [busFaktor/Proxmox#1]
## 🌟 EPIC

Install Proxmox on our netcup develop server.

### Todo

- [ ] setup our netcup dev server for Proxmox
  - [x] install Debian 12
  - [x] install Proxmox
    - [ ] leftovers:
      - [ ] netcup states: `Das Programm qemu-guest-agent ist auf Ihrem Server nicht installiert. Wir empfehlen Ihnen, das Programm zu installieren. Der qemu-guest-agent ist unter anderem für ein sicheres Herunterfahren des Servers und andere Funktionen, welche das SCP nutzt, verantwortlich.`
      - [ ] make ssh possible from local terminal again
  - [x] install NGINX Proxy Manager
    - [ ] leftovers
      - [ ] Web Interface Via Nginx Proxy: https://pve.proxmox.com/wiki/Web_Interface_Via_Nginx_Proxy
  - [ ] Firewall
  - [x] give server a subdomain of busfaktor.org: `proxmox.busfaktor.org`
  - [ ] give netcup logins to the server product and control panel to the admins
  - [ ] give access to Ulf
- [ ] create contained servers for:
  - [ ] website `ocelot.social`
  - [ ] website `docs.ocelot.social`
  - [ ] website `busfaktor.org`
  - [ ] Uptime Kuma like on `https://uptime.it4c.dev/dashboard`
    - [ ] monitor the websites:
      - [ ] website `ocelot.social`
      - [ ] website `docs.ocelot.social`
      - [ ] website `busfaktor.org
      - [ ] website `stage.ocelot.social`
  - [ ] 1-click deployment of an ocelot.social instance
- [ ] docs for setting up and usage of Proxmox
  - [ ] hint to websites `docs.ocelot.social` and `ocelot.social`
    
#### netcup Server

- server setup or update with Debian 12

#### Proxmox

- install Proxmox:
  - https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_12_Bookworm
- user management:
  - https://pve.proxmox.com/wiki/User_Management
  - https://pve.proxmox.com/pve-docs/chapter-pveum.html#_privileges

#### nginx-proxy-manager Creation

- per script without Docker:
  - https://github.com/ej52/proxmox-scripts/tree/main
  - https://medium.com/@spidey169/detailed-guide-for-configuring-proxmox-and-running-rpc-full-node-on-proxmox-container-installing-7bc22d30be5f
  - `Proxy Host` configuration for a container
    - https://gnulinux.ch/nginx-proxy-manager

#### Network and Bridge Creation

- instruction:
  - interfaces file: https://medium.com/@spidey169/detailed-guide-for-configuring-proxmox-and-running-rpc-full-node-on-proxmox-container-installing-7bc22d30be5f
  - !!! does not work: Creating a LXC container without modifying your network interfaces: https://wiki.alpinelinux.org/wiki/LXC#Creating_a_LXC_container_without_modifying_your_network_interfaces
    - we have to change the instruction for Debian 12

#### Container Creation

- instruction:
  - Creating Containers in Proxmox: https://linuxhandbook.com/proxmox-create-container/
  - LXC containers overview: http://download.proxmox.com/images/system/
  - alpine-3.17-default download link:
    - http://download.proxmox.com/images/system/alpine-3.17-default_20221129_amd64.tar.xz

#### Specific Containers

- ocelot.social-website
  - configure network IPv4 (is now DHCP)

### Procedure for a dedicated (Hetzner) servers using Proxmox VE

- https://medium.com/@spidey169/detailed-guide-for-configuring-proxmox-and-running-rpc-full-node-on-proxmox-container-installing-7bc22d30be5f
